github.com:
    users:
        gergocs:
            oauth_token: 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
    git_protocol: https
    user: gergocs
    oauth_token: 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
